### ISSUE TITLE
Listing in snap store does not match upstream listing

### ISSUE THREAD

**Issue by qwertychouskie** [diddlesnaps/supertuxkart#10]
First, SuperTuxKart is one word ;P

Ideally, the app store listing and screenshots should match [the upstream supertuxkart.appdata.xml](https://github.com/supertuxkart/stk-code/blob/master/data/supertuxkart.appdata.xml).

BTW, thanks for your work in supporting STK installs using the Snap format!  If I can help out, let me know (I maintain the STK PPA).  I usually know when a new version is about to release, so I could help make sure that the snap gets updated with the latest betas, RCs, and stable builds as soon as they come out.

Interesting fact, for a long time, 0.9.1 had more users than 0.9.2, best we could tell is because 0.9.1 was packaged in the latest Ubuntu LTS.  However, when 1.0 was released, it quickly overtook 0.9.3 (https://online.supertuxkart.net/stats/?clients), meaning this snap release probably had a role in it, since snap updates go to all supported Ubuntu versions.

**Comment by lucyllewy** [comment]
Sorry it took me so long to get to this. I think the store listing is now correct: https://snapcraft.io/supertuxkart. Please can you check and let me know if I missed anything? Many thanks :-)

Thanks also for your volunteering to keep me updated on new releases, that will be very helpful to me to getting prompt updates out. If the STK team wish to take over maintaining this I am happy to hand over the reigns, but equally I am happy to continue with maintenance if that is preferred.

**Comment by qwertychouskie** [comment]
Thanks for updating, it looks good!  Speaking of new releases, 1.1-rc1 was just released.  The build process is pretty much the same except that Harfbuzz was added as a dependency.

Thanks for maintaining this build!

**Comment by qwertychouskie** [comment]
Closing this issue as I haven't found any remaining issues with the listing.
