### ISSUE TITLE
Blurry icon

### ISSUE THREAD

**Issue by Feichtmeier** [diddlesnaps/supertuxkart#11]
Hello there - thanks for snapping supertuxkart!

I think the icon in the snap version is really blurry
![grafik](https://user-images.githubusercontent.com/15329494/71543683-f960bb00-2975-11ea-8abe-6fc983287d0d.png)

Is this the official supertux icon? If yes - maybe the guys need help for a better icon?
Best regards,
Frederik

**Comment by lucyllewy** [comment]
This fix will make its way to the store soon.
