### ISSUE TITLE
SuperTuxKart 1.1 released

### ISSUE THREAD

**Issue by pixelr0** [diddlesnaps/supertuxkart#12]
SuperTuxKart 1.1 released http://blog.supertuxkart.net/2020/01/supertuxkart-11-released.html

**Comment by Benau** [comment]
Btw would be good to use latest freetype and harfbuzz for it because old version of them display emoji and country flag wrongly

**Comment by Benau** [comment]
btw you can discard fontconfig + icu + graphite2 deps when building harfbuzz as they are not needed for stk (to save few KB in snap if you want)

harfbuzz itself has its own ucdn which is enough for stk

**Comment by lucyllewy** [comment]
1.1 is now in stable :-)
