### ISSUE TITLE
Bundle the needed `openh264` library as bootstrap often fails

### ISSUE THREAD

**Issue by qwertychouskie** [diddlesnaps/supertuxkart#13]
As seen in issue #7 and https://www.raspberrypi.org/forums/viewtopic.php?f=78&t=195612&start=25#p1698734, the bootstrap script often fails.  Is there any particular reason to have this bootstrap rather than just bundling the library like all the other libraries?  Alternatively, it may be better to just build with `-DBUILD_RECORDER=0` which will eliminate the dependency.

**Comment by lucyllewy** [comment]
The download step is required for Cisco to pay the MPEG/H.264 licensing fees and therefore to get a license to use the patent-encumbered H.264 for free. I could use a library that doesn't officially license the H.264 patents but that opens both users and myself to potential legal action for distributing and using a patent-encumbered software without paying the required licensing fee. (history has shown that OSS software has generally been unchallenged by MPEG but that isn't a guarantee)

**Comment by lucyllewy** [comment]
I _thought_ I had added a fallback if the library isn't found to use a version that is included in the snap on the basis that most people will get the downloaded license-paid version but if that fails they still get a working game. I'll have another look at this to see if there's a bug there.

**Comment by EnsignRutherford** [comment]
I am having a heck of a time getting supertuxkart to run on the Raspberry Pi 4.  I've gotten to the point where I've installed from snap and when I try to execute /snap/supertuxkart/408/usr/bin/supertuxkart I'm getting:

pi@playbox4:/snap/supertuxkart/408/usr/bin$ ./supertuxkart
./supertuxkart: error while loading shared libraries: libopenglrecorder.so.0: cannot open shared object file: No such file or directory

**Comment by qwertychouskie** [comment]
If you're worried about legal issues, wouldn't it be better to just build STK with `-DBUILD_RECORDER=0`?  The recorder is only available in Artist Debug Mode anyways, most people don't even know/care the feature exists.

**Comment by lucyllewy** [comment]
I'll do that. Right now, though the game won't start on a pi at all even when there is an appropriate h264 library. seems that the issue there is with the opengl... I'm investigating - the build in the store's `edge` channel shows the issue.
