### ISSUE TITLE
supertuxkart (edge) 0.10-rc1 doesn't work

### ISSUE THREAD

**Issue by pixelr0** [diddlesnaps/supertuxkart#3]
doesn't start (Ubuntu 16.04)

snap run supertuxkart
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0curl: (6) Could not resolve host: ciscobinary.openh264.org
bunzip2: Can't open input file /home/pixel/snap/supertuxkart/64/openh264/libopenh264.so.bz2: No such file or directory.
/snap/supertuxkart/64/usr/bin/supertuxkart: error while loading shared libraries: libopenh264.so.4: cannot open shared object file: No such file or directory

------------------

~$ supertuxkart 
ln: failed to create symbolic link '/home/pixel/snap/supertuxkart/64/openh264/libopenh264.so.3': File exists
ln: failed to create symbolic link '/home/pixel/snap/supertuxkart/64/openh264/libopenh264.so.4': File exists
/snap/supertuxkart/64/usr/bin/supertuxkart: error while loading shared libraries: libopenh264.so.4: cannot open shared object file: No such file or directory

**Comment by lucyllewy** [comment]
Something is (was) wrong with your system that prevents DNS from resolving the domain name "ciscobinary.openh264.org". This is unrelated to the snap.

The relevant part of the output is:

```plain
curl: (6) Could not resolve host: ciscobinary.openh264.org
```

**Comment by pixelr0** [comment]
oh :D 
makes sense 
closing issue
