### ISSUE TITLE
1.0 released

### ISSUE THREAD

**Issue by brlin-tw** [diddlesnaps/supertuxkart#4]
Refer [Blog - Supertuxkart](http://blog.supertuxkart.net/2019/04/supertuxkart-10-release.html)

**Comment by lucyllewy** [comment]
Thanks, the builder is running now (for changeset 2bef1e5) :-)

**Comment by brlin-tw** [comment]
Would you mind if I change it to directly build from the source repository?

**Comment by lucyllewy** [comment]
If I remember correctly, I couldn't reliably get the media assets when building from the version-controlled repository. The tarballs include everything needed, but building from the repo doesn't. If you can find a way to reliably get the correct assets for the version being built at any point in time then please do file a PR :-) It's not clear to me how the assets are versioned...
