### ISSUE TITLE
Gamepads not recognized

### ISSUE THREAD

**Issue by qwertychouskie** [diddlesnaps/supertuxkart#9]
https://forum.freegamedev.net/viewtopic.php?f=17&t=12693

Seems gamepads aren't recognized in this build, probably due to Snap's sandboxing and the necessary permission not being assigned.

**Comment by qwertychouskie** [comment]
`sudo snap connect supertuxkart:joystick` fixed things for me.  Would be nice to see this fixed before 1.1 hits the stable channel.

**Comment by lucyllewy** [comment]
I've requested that joystick be connected automatically: https://forum.snapcraft.io/t/auto-connect-joystick-for-supertuxkart/15005

**Comment by lucyllewy** [comment]
`joystick` is now automatically connected by the store.
